//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TECHSHOP
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        public int ID_ORDER { get; set; }
        public int ID_PRODUCT { get; set; }
        public int PRICEALL { get; set; }
        public int COUNT { get; set; }
        public string STATUSO { get; set; }
    
        public virtual PRODUCTS PRODUCTS { get; set; }
    }
}
